### PR TITLE
Git week2

### PR DESCRIPTION
**Pull request by maccrin**

### CODE REVIEW

**Review by marta-ov — CHANGES_REQUESTED** [review]
The PR should be from `feature/veggies` to `git-week2`, so can you change that please? :)

**Comment by maccrin** [comment]
> 

Hi Marta
Thank You very much for your time,yes definitely I will fix it,just one question can I do it in same branch or need to make a new one..
🙂

**Comment by marta-ov** [comment]
You should be able to see an "Edit" button somewhere to the right of the PR title (i cannot because it's not my repository). If  you click there you can edit the PR branches :)

image

**Comment by maccrin** [comment]
> You should be able to see an "Edit" button somewhere to the right of the PR title (i cannot because it's not my repository). If you click there you can edit the PR branches :)
> 
> image

👍🏻 Thanks, will fix.

**Comment by maccrin** [comment]
> > You should be able to see an "Edit" button somewhere to the right of the PR title (i cannot because it's not my repository). If you click there you can edit the PR branches :)
> > image
> 
> 👍🏻 Thanks, will fix.
I am able to change the base branch to git-week2 but when try to change the other branch fruites/veggies it shows me.lots of earlier commit which are in other branch of different module ..
Some mess happened I can guess so I didn't take risk to change the branch :(
Can I redo the whole stuff with different branch name.

**Comment by marta-ov** [comment]
Sure! Go ahead! :)

**Comment by maccrin** [comment]
> 

Thank You 😊

**Pull request closed without merging**
