### PR TITLE
3rd veggy changed and 2 more added

### PR DESCRIPTION
**Pull request by maccrin**

### CODE REVIEW

**Comment by marta-ov** [comment]
Almost there :)
You're missing step 7

**Comment by maccrin** [comment]
> Almost there :) You're missing step 7

Hi Marta
I just did step 7,could you please check :),Thank You .

**Comment by marta-ov** [comment]
Yes! Well done! :)
You can merge this PR and then create another PR from `git-week2` to `main` and merge it too :)

**Review by marta-ov — APPROVED** [review]

**Comment by maccrin** [comment]
> Yes! Well done! :) You can merge this PR and then create another PR from `git-week2` to `main` and merge it too :)

Thank You for your patience and effort for us 🙏🏾.

**Pull request merged**
