### PR TITLE
Git week1

### PR DESCRIPTION
**Pull request by maccrin**
GIT WEEK 1 HOMEWORK

### CODE REVIEW

**Review by marta-ov — CHANGES_REQUESTED** [review]
This is great! :D
I just have one last task for you, to mimic the process of implementing mentor feedback: can you add one more country name to the file countries.txt, commit, and push please?
And then you'll see that the new commit shows up on this PR automatically :)

**Comment by maccrin** [comment]
> This is great! :D I just have one last task for you, to mimic the process of implementing mentor feedback: can you add one more country name to the file countries.txt, commit, and push please? And then you'll see that the new commit shows up on this PR automatically :)

Sure I will do the same, thank you.

**Comment by maccrin** [comment]
> This is great! :D I just have one last task for you, to mimic the process of implementing mentor feedback: can you add one more country name to the file countries.txt, commit, and push please? And then you'll see that the new commit shows up on this PR automatically :)

Hi Marta
I just  added one more country name in as per your advice and yes that is reflecting as another commit in PR,please check.
Thank You

**Review by marta-ov — APPROVED** [review]
This is great, thank you! You can now merge your PR :)

**Comment by maccrin** [comment]
> This is great, thank you! You can now merge your PR :)

Thank you very much your all help and patience :)

**Pull request merged**
